application: mikenz2011
version: 1
runtime: python
api_version: 1

handlers:

- url: /scripts
  static_dir: static/scripts
  
- url: /css
  static_dir: static/css
  
- url: /.*
  script: asklogin.py

